apiVersion: skaffold/v2beta1
kind: Config
metadata:
  name: energyplus-backend
build:
  tagPolicy:
    gitCommit:
      {}
  artifacts:
  - image: energyplus-backend
    context: .
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml
    - k8s/service.yaml
    - k8s/ingress.yaml